# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ac1c26b81a2201407bfd371402c19d8e4a101d9c16344a8c9357a52b71c1cdef8f2f2f0c28912dc11006bc04ffcade7462dd897c75e1174010bdc54ae3bc62

test:
  secret_key_base: 27163f77867dc3b2e8f8d254ef20b5213d2c3dca35fa16c6c21ce97c6464dc3129578daa04bfbfe5ebd654101583ae7ed2d9f3075d7edbaf4837f30acca2b0e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
